---
- name: Install PostgreSQL PLPerl
  apt:
    name: "postgresql-plperl-{{ postgresql_version }}"
    state: present

- name: Install needed perl libraries
  apt:
    name: "{{ evergreen_database_perl_dependencies }}"
    state: present

- name: Install cpanm for ansible
  apt:
    name: cpanminus
    state: present

- name: Install MARC::File::XML for PostgreSQL
  cpanm:
    name: "MARC::File::XML"

- name: Install String::KeyboardDistance for PostgreSQL
  cpanm:
    name: "String::KeyboardDistance"

- name: Install Text::Levenshtein::Damerau::XS for PostgreSQL
  cpanm:
    name: "Text::Levenshtein::Damerau::XS"