INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '520', 'tr-TR', 'Şiir');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '897', 'tr-TR', 'Şiir');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1565', 'tr-TR', 'Şiir');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1585', 'tr-TR', 'Şiir');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '226', 'tr-TR', 'Kırgızca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '317', 'tr-TR', 'Norveççe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '3', 'tr-TR', 'LCCN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '12', 'tr-TR', 'LCCN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('czifm.label', '5', 'tr-TR', 'LCCN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '179', 'tr-TR', 'Hititçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'en-CA', 'tr-TR', 'İngilizce (Kanada)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '470', 'tr-TR', 'Galce');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '205', 'tr-TR', 'Japonca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'hy-AM', 'tr-TR', 'Ermenice');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'hy-AM', 'tr-TR', 'Ermenice');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'arm', 'tr-TR', 'Ermenice');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'en-US', 'tr-TR', 'Amerikan İngilizcesi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'ady', 'tr-TR', 'Adigece');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '445', 'tr-TR', 'Türkmence');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '69', 'tr-TR', 'Katalanca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1155', 'tr-TR', 'Letonca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '247', 'tr-TR', 'Latince');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1007', 'tr-TR', 'Arnavutça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'alb', 'tr-TR', 'Arnavutça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '455', 'tr-TR', 'Uygurca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '204', 'tr-TR', 'Japonca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '294', 'tr-TR', 'Çoklu diller');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '286', 'tr-TR', 'Maltaca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cmf.label', '4', 'tr-TR', 'Alternatif Başlık');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cmc.label', 'title', 'tr-TR', 'Başlık');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '5', 'tr-TR', 'Başlık');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '14', 'tr-TR', 'Başlık');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aba.name', 'title', 'tr-TR', 'Başlık');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('czifm.label', '1', 'tr-TR', 'Başlık');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '40', 'tr-TR', 'Bambara (Mali)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccs.name', '14', 'tr-TR', 'Hasarlı');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '150', 'tr-TR', 'Gürcüce');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '355', 'tr-TR', 'Romance (Diğer)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '119', 'tr-TR', 'İngilizce');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1098', 'tr-TR', 'Gürcüce');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '182', 'tr-TR', 'Macarca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '463', 'tr-TR', 'Vietnamca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '112', 'tr-TR', 'Hollandaca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '331', 'tr-TR', 'Türkçe, Osmanlıca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'es-MX', 'tr-TR', 'İspanyolca (Meksika)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '121', 'tr-TR', 'Esperanto');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '123', 'tr-TR', 'Esperanto');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '203', 'tr-TR', 'İtalyanca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '241', 'tr-TR', 'Ladino');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'ava', 'tr-TR', 'Avarca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '347', 'tr-TR', 'Portekizce');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '89', 'tr-TR', 'Kernevekçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '419', 'tr-TR', 'Tacikçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '427', 'tr-TR', 'Tacikçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '76', 'tr-TR', 'Çağatayca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'ace', 'tr-TR', 'Çince');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '429', 'tr-TR', 'Tayca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'es-MX', 'tr-TR', 'Meksika İspanyolcası');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'es-US', 'tr-TR', 'Meksika İspanyolcası');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1323', 'tr-TR', 'Makedonca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '522', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '553', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '793', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '806', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '879', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '917', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '999', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1006', 'tr-TR', 'Bilinmeyen');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'abk', 'tr-TR', 'Ahbazca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cmf.label', '21', 'tr-TR', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '56', 'tr-TR', 'Baltık (Diğer)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '72', 'tr-TR', 'Baltık (Diğer)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'arc', 'tr-TR', 'Aramice');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '248', 'tr-TR', 'Letonca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'ru-RU', 'tr-TR', 'Rusça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'ru-RU', 'tr-TR', 'Rusça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '360', 'tr-TR', 'Rusça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '42', 'tr-TR', 'Baskça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '75', 'tr-TR', 'Çeçence');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '367', 'tr-TR', 'Sanskritçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'bak', 'tr-TR', 'Başkırca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '174', 'tr-TR', 'İbranice');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('pgt.name', '15', 'tr-TR', 'Gönüllüler');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('pgt.name', '1', 'tr-TR', 'Kullanıcılar');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '456', 'tr-TR', 'Ukrayna Dili');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '63', 'tr-TR', 'Bulgarca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '371', 'tr-TR', 'Sırpça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1045', 'tr-TR', 'Bulgarca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '459', 'tr-TR', 'Urduca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '460', 'tr-TR', 'Özbekçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '59', 'tr-TR', 'Bretonca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '448', 'tr-TR', 'Türkçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '449', 'tr-TR', 'Baltık (Diğer)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '478', 'tr-TR', 'Yidiş');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1232', 'tr-TR', 'Sırpça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '197', 'tr-TR', 'İnguşca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '77', 'tr-TR', 'Çince');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'ara', 'tr-TR', 'Arapça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '136', 'tr-TR', 'Fransızca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '57', 'tr-TR', 'Boşnakça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '218', 'tr-TR', 'Kazakça');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '44', 'tr-TR', 'Baltık (Diğer)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cmf.label', '19', 'tr-TR', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '6', 'tr-TR', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '15', 'tr-TR', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('vqbrad.description', '6', 'tr-TR', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('czifm.label', '4', 'tr-TR', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '314', 'tr-TR', 'Norveççe (Bokmål)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '330', 'tr-TR', 'Osetçe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cmf.label', '18', 'tr-TR', 'ISBN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '2', 'tr-TR', 'ISBN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '11', 'tr-TR', 'ISBN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('vqbrad.description', '5', 'tr-TR', 'ISBN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('czifm.label', '3', 'tr-TR', 'ISBN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cit.name', '3', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aurt.label', '6', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '555', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '807', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '880', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '901', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '964', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '977', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '987', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1000', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1569', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1589', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1602', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1614', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1626', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1638', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1648', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1657', 'tr-TR', 'Diğer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'en-CA', 'tr-TR', 'Kanada İngilizcesi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '48', 'tr-TR', 'Bengalce');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'fi-FI', 'tr-TR', 'Fince');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'fi-FI', 'tr-TR', 'Fince');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '133', 'tr-TR', 'Fince');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '263', 'tr-TR', 'Makedonca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '252', 'tr-TR', 'Litvanca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', '1151', 'tr-TR', 'Litvanca');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccvm.value', 'aus', 'tr-TR', 'Avustralya dilleri');
