---
name: Ansible Lint

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: "./"
          args: "--exclude=meta"
