---
name: Ansible Lint

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install role dependencies
        run: ansible-galaxy install -r molecule/default/requirements.yml
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v26.4.0
        with:
          targets: "./"
